AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ff-sam

  Sample SAM Template for ff-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
  CreateFlagFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: flags/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Flags:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /flags
            Method: get
            RequestParameters:
              method.request.querystring.name:
                Required: true
                Caching: false
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MyS3Bucket
      Environment:
        Variables:
          FLAGS_BUCKET: !Ref MyS3Bucket

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  createFlagApi:
    Description: API Gateway endpoint URL for Prod stage for creating flags
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/flags/"
  CreateFlagFunction:
    Description: Create Flag Function ARN
    Value: !GetAtt CreateFlagFunction.Arn
  CreateFlagFunctionIamRole:
    Description: Implicit IAM Role created for create flag function
    Value: !GetAtt CreateFlagFunctionRole.Arn
